// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVNqZb03qJTj9MsK1sE_ETioq0kzNZe64',
    appId: '1:793718006183:android:76ee6ee246e7b16ca95682',
    messagingSenderId: '793718006183',
    projectId: 'e-commerce-24cd6',
    storageBucket: 'e-commerce-24cd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8KAZ2_U6c92KCVtSXbyTOjmZCTfR3VLA',
    appId: '1:793718006183:ios:dd74e184b1410c08a95682',
    messagingSenderId: '793718006183',
    projectId: 'e-commerce-24cd6',
    storageBucket: 'e-commerce-24cd6.firebasestorage.app',
    androidClientId: '793718006183-mjn0ed4g0o84l9qhc0s41rpk3c8jb0o5.apps.googleusercontent.com',
    iosClientId: '793718006183-2sf7i707io842l2rhec7kk9l34l1m093.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
